name: FlyCraft
version: 1.2
main: me.streakstudios.flyCraft.FlyCraft
commands:
  fly:
    description: FlyCraft commands
    usage: /fly [reload|help]
    permission: fly.fly
    permission-message: You do not have permission to use this command.
permissions:
  fly.use:
    description: Allows the use of the fly command
    default: op
  fly.reload:
    description: Allows the use of the /fly reload command
    default: op
